spring:
  application:
    name: everycart-api
  profiles:
    default: local

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  show-actuator: false
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
